DROP DATABASE IF EXISTS twitch_padatables;
CREATE DATABASE twitch_padatables CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE twitch_padatables;

CREATE TABLE peliculas(
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  SINOPSIS TEXT,
  ANIO YEAR,
  GENERO VARCHAR(100),
  DIRECTOR VARCHAR(100),
  PUNTAJE FLOAT( 4,2 )
);

INSERT INTO peliculas (NOMBRE, SINOPSIS, ANIO, GENERO, DIRECTOR, PUNTAJE )
VALUES 
  ('La cosa', 'Una cosa viene y mata a todos en el sur', '1976', 'Terror', 'Jhon Carpenter', '9.5'),
  ('IT', 'Un payaso que es en realidad un bogart y toma la forma de que lo más te asuste. Come pibes (como el bambino)', '1990', 'Terror', 'Stephen King', '7'),
  ('Deadpool', 'El mecenario bocazas, pero la versión copada de Ryan Raynolds (2016), no la versión poronga de Ryan Raynolds (2009)', '2016', 'Comics', 'Ni idea', '8'),
  ('Rocky', 'Silvestre Está Alone hace su debut a lo grande como un boxeador insipirado en Rocky Marciano, pero se llama Balboa', '1976', 'Accion, Deporte', 'John G Avildsen', '8'),
  ('Avatar', 'Unos pitufos de 2.30mt de altura de otro planeta, se enfrentan al sindicato de la construcción de Caballito, en una versión aggiornada de Civilización vs Barbarie', '2009', 'Aventuras', 'James Cameron', '10'),
  ('Matrix', 'Las wachowski haciendo su mejor película de todos los tiempos (al menos la uno) que nos demostró que el elegido, no necesariamente tiene que tener expresividad en su rostro.', '1999', 'Sci Fi', 'Lana Wachowski y Lili Wachowski', '9.9'),
  ('Fiesta de Salchichas', 'Una inocente película para niños, del estudio que te trajo The Emoji Movie, pero son salchichas y panes de salchichas que te van a hacer replantear ponerle o no mostaza.', '2016', 'Comedia', 'Seth Rogen', '7'),
  ('Halcón', 'Un mal padre se tiene que hacer cargo de su hijo, y en vez de educarlo lo lleva por EEUU a jugar pulseadas.', '2016', 'Comedia', 'Seth Rogen', '7'),
  ('El Padrino', 'Un Don hace ofertas que no puedes rechazar', '1972', 'Drama', 'Francis Ford Coppola', '9.2'),
  ('Titanic', 'Barco choca con iceberg, romance flota', '1997', 'Romance', 'James Cameron', '8.9'),
  ('Star Wars: Episodio IV', 'Granjero espacial destruye estrella de la muerte', '1977', 'Ciencia ficción', 'George Lucas', '9.0'),
  ('Pulp Fiction', 'Historias entrelazadas de criminales con diálogos cool', '1994', 'Crimen', 'Quentin Tarantino', '8.9'),
  ('Forrest Gump', 'Hombre simple vive vida extraordinaria, corre mucho', '1994', 'Drama', 'Robert Zemeckis', '8.8'),
  ('El Rey León', 'Cachorro de león supera trauma familiar, recupera reino', '1994', 'Animación', 'Roger Allers', '8.5'),
  ('Matrix', 'Hacker descubre que vivimos en una simulación', '1999', 'Ciencia ficción', 'Lana Wachowski', '8.7'),
  ('Jurassic Park', 'Parque temático de dinosaurios, ¿qué podría salir mal?', '1993', 'Aventura', 'Steven Spielberg', '8.6'),
  ('El Silencio de los Corderos', 'Agente novata entrevista a caníbal para atrapar asesino', '1991', 'Thriller', 'Jonathan Demme', '8.6'),
  ('Volver al Futuro', 'Adolescente viaja al pasado, casi borra su existencia', '1985', 'Ciencia ficción', 'Robert Zemeckis', '8.5'),
  ('Gladiador', 'General romano caído en desgracia busca venganza', '2000', 'Acción', 'Ridley Scott', '8.5'),
  ('El Señor de los Anillos: El Retorno del Rey', 'Hobbits destruyen joya, salvan Tierra Media', '2003', 'Fantasía', 'Peter Jackson', '9.0'),
  ('Inception', 'Ladrón de sueños intenta plantar una idea', '2010', 'Ciencia ficción', 'Christopher Nolan', '8.8'),
  ('El Club de la Pelea', 'Hombre insomne crea club secreto, caos enseguida', '1999', 'Drama', 'David Fincher', '8.8'),
  ('E.T., el Extraterrestre', 'Niño ayuda a alienígena adorable a volver a casa', '1982', 'Ciencia ficción', 'Steven Spielberg', '8.6'),
  ('Los Vengadores', 'Superhéroes se unen para salvar la Tierra', '2012', 'Acción', 'Joss Whedon', '8.0'),
  ('Parque Jurásico', 'Dinosaurios escapan, caos y persecuciones', '1993', 'Aventura', 'Steven Spielberg', '8.2'),
  ('El Exorcista', 'Niña poseída, sacerdotes intentan ayudar', '1973', 'Terror', 'William Friedkin', '8.1'),
  ('Casablanca', 'Dueño de café elige entre amor y deber', '1942', 'Romance', 'Michael Curtiz', '8.5'),
  ('Psicosis', 'Motel con dueño perturbado, ducha peligrosa', '1960', 'Thriller', 'Alfred Hitchcock', '8.5'),
  ('Alien', 'Tripulación espacial contra monstruo imparable', '1979', 'Ciencia ficción', 'Ridley Scott', '8.5'),
  ('Blade Runner', 'Detective caza androides en futuro distópico', '1982', 'Ciencia ficción', 'Ridley Scott', '8.1'),
  ('La Lista de Schindler', 'Empresario salva vidas durante el Holocausto', '1993', 'Drama', 'Steven Spielberg', '9.0'),
  ('El Resplandor', 'Familia cuida hotel, padre enloquece', '1980', 'Terror', 'Stanley Kubrick', '8.4'),
  ('Terminator 2: El Juicio Final', 'Robot del futuro protege a adolescente rebelde', '1991', 'Acción', 'James Cameron', '8.6'),
  ('Tiburón', 'Pez grande aterroriza playa, barco lo persigue', '1975', 'Thriller', 'Steven Spielberg', '8.1'),
  ('La La Land', 'Aspirantes a artistas bailan y cantan en L.A.', '2016', 'Musical', 'Damien Chazelle', '8.0'),
  ('El Gran Lebowski', 'Confunden a vago con millonario, caos cómico', '1998', 'Comedia', 'Joel Coen', '8.1'),
  ('Interestelar', 'Viaje espacial para salvar la humanidad', '2014', 'Ciencia ficción', 'Christopher Nolan', '8.7'),
  ('El Pianista', 'Músico sobrevive al Holocausto en Varsovia', '2002', 'Drama', 'Roman Polanski', '8.5'),
  ('Coco', 'Niño viaja al mundo de los muertos, descubre secretos familiares', '2017', 'Animación', 'Lee Unkrich', '8.4'),
  ('El Lobo de Wall Street', 'Corredor de bolsa vive al límite, FBI no aprueba', '2013', 'Biografía', 'Martin Scorsese', '8.2'),
  ('Amélie', 'Camarera parisina mejora vidas ajenas, encuentra amor', '2001', 'Comedia', 'Jean-Pierre Jeunet', '8.3'),
  ('El Laberinto del Fauno', 'Niña descubre mundo mágico durante guerra civil', '2006', 'Fantasía', 'Guillermo del Toro', '8.2'),
  ('Whiplash', 'Baterista ambicioso sufre bajo profesor tiránico', '2014', 'Drama', 'Damien Chazelle', '8.5'),
  ('El Viaje de Chihiro', 'Niña trabaja en baño de espíritus para salvar padres', '2001', 'Animación', 'Hayao Miyazaki', '8.6'),
  ('Django Sin Cadenas', 'Esclavo liberado busca venganza y a su esposa', '2012', 'Western', 'Quentin Tarantino', '8.4'),
  ('El Gran Hotel Budapest', 'Conserje y botones viven aventuras en hotel excéntrico', '2014', 'Comedia', 'Wes Anderson', '8.1'),
  ('Parásitos', 'Familia pobre se infiltra en casa de ricos, caos', '2019', 'Thriller', 'Bong Joon-ho', '8.5'),
  ('El Caballero de la Noche', 'Murciélago contra payaso, ciudad en caos', '2008', 'Acción', 'Christopher Nolan', '9.0'),
  ('La Forma del Agua', 'Mujer muda se enamora de criatura anfibia', '2017', 'Fantasía', 'Guillermo del Toro', '7.3'),
  ('Perdida', 'Esposa desaparece, marido sospechoso, nada es lo que parece', '2014', 'Thriller', 'David Fincher', '8.1'),
  ('Her', 'Hombre se enamora de sistema operativo inteligente', '2013', 'Drama', 'Spike Jonze', '8.0'),
  ('Mad Max: Furia en la Carretera', 'Persecución post-apocalíptica por agua y libertad', '2015', 'Acción', 'George Miller', '8.1'),
  ('El Discurso del Rey', 'Rey tartamudo supera miedo a hablar en público', '2010', 'Drama', 'Tom Hooper', '8.0'),
  ('Memento', 'Hombre con amnesia busca venganza usando notas', '2000', 'Thriller', 'Christopher Nolan', '8.4'),
  ('El Sexto Sentido', 'Psicólogo ayuda a niño que ve muertos', '1999', 'Thriller', 'M. Night Shyamalan', '8.2'),
  ('Rescatando al Soldado Ryan', 'Misión para salvar a un soldado en la WWII', '1998', 'Guerra', 'Steven Spielberg', '8.6'),
  ('La Vida es Bella', 'Padre protege a hijo del horror del Holocausto', '1997', 'Comedia-drama', 'Roberto Benigni', '8.6'),
  ('Ciudad de Dios', 'Jóvenes crecen en violenta favela brasileña', '2002', 'Crimen', 'Fernando Meirelles', '8.6'),
  ('El Gran Dictador', 'Barbero judío confundido con dictador fascista', '1940', 'Comedia', 'Charles Chaplin', '8.4'),
  ('Apocalypse Now', 'Capitán busca coronel loco en Vietnam', '1979', 'Guerra', 'Francis Ford Coppola', '8.4'),
  ('Bastardos sin Gloria', 'Judíos planean venganza contra nazis en cine', '2009', 'Guerra', 'Quentin Tarantino', '8.3'),
  ('El Bueno, el Malo y el Feo', 'Tres pistoleros compiten por tesoro enterrado', '1966', 'Western', 'Sergio Leone', '8.8'),
  ('Réquiem por un Sueño', 'Adicciones destruyen vidas de cuatro personas', '2000', 'Drama', 'Darren Aronofsky', '8.3'),
  ('El Apartamento', 'Empleado presta piso a jefes para aventuras', '1960', 'Comedia', 'Billy Wilder', '8.3'),
  ('Eterno Resplandor de una Mente sin Recuerdos', 'Pareja borra recuerdos mutuos, se reencuentran', '2004', 'Drama', 'Michel Gondry', '8.3'),
  ('Taxi Driver', 'Veterano perturbado planea violencia en Nueva York', '1976', 'Drama', 'Martin Scorsese', '8.2'),
  ('El Profesional', 'Asesino adopta a niña huérfana, le enseña oficio', '1994', 'Acción', 'Luc Besson', '8.5'),
  ('Amélie', 'Camarera parisina mejora vidas ajenas, encuentra amor', '2001', 'Comedia', 'Jean-Pierre Jeunet', '8.3'),
  ('Toy Story', 'Juguetes cobran vida, rivalizan por afecto de niño', '1995', 'Animación', 'John Lasseter', '8.3'),
  ('Regreso al Futuro', 'Adolescente viaja al pasado, altera su propia historia', '1985', 'Ciencia ficción', 'Robert Zemeckis', '8.5'),
  ('El Show de Truman', 'Hombre descubre que su vida es un reality show', '1998', 'Comedia-drama', 'Peter Weir', '8.2'),
  ('Cidade de Deus', 'Jóvenes crecen en violenta favela brasileña', '2002', 'Crimen', 'Fernando Meirelles', '8.6'),
  ('El Laberinto del Fauno', 'Niña descubre mundo mágico durante guerra civil', '2006', 'Fantasía', 'Guillermo del Toro', '8.2'),
  ('Belleza Americana', 'Hombre en crisis de mediana edad redescubre la vida', '1999', 'Drama', 'Sam Mendes', '8.3'),
  ('Intocable', 'Millonario tetrapléjico contrata cuidador poco convencional', '2011', 'Comedia-drama', 'Olivier Nakache', '8.5'),
  ('La Vida de los Otros', 'Agente de la Stasi espía a escritor, cambia su vida', '2006', 'Drama', 'Florian Henckel von Donnersmarck', '8.4'),
  ('Oldboy', 'Hombre busca venganza tras 15 años de encierro', '2003', 'Thriller', 'Park Chan-wook', '8.4'),
  ('El Pianista', 'Músico judío sobrevive en Varsovia durante el Holocausto', '2002', 'Drama', 'Roman Polanski', '8.5'),
  ('Snatch: Cerdos y Diamantes', 'Boxeador y diamante causan caos en Londres', '2000', 'Crimen', 'Guy Ritchie', '8.3'),
  ('V de Vendetta', 'Enmascarado lucha contra gobierno totalitario', '2005', 'Acción', 'James McTeigue', '8.2'),
  ('El Secreto de sus Ojos', 'Investigador obsesionado con caso sin resolver', '2009', 'Drama', 'Juan José Campanella', '8.2');